### ISSUE TITLE
Update the Tulu Sri font to 20.20 to fix the otthakshara issue

### ISSUE THREAD

**Issue by yajnesh** [chandukaup/convert2tulu#1]
![image](https://user-images.githubusercontent.com/921113/115959977-9b71c280-a52c-11eb-81a2-3d3bd9f5088a.png)

When there is otthakshra, the font misbehaves, this is how ಸ್ತೋ is getting displayed. I believe with Tulu Sri 20.20, the issue should be resolved. https://thetulufont.com/downoad-the-tulu-font

**Comment by chandukaup** [comment]
Hey Yajnesh, Thanks.. I just upgraded the font to Tulu Sri 20.20. Can you check?

**Comment by yajnesh** [comment]
It's working fine now. thanks for fixing it.
